### PR TITLE
Client: Handle all reply codes in range 400-599

### LINKED ISSUE #27: Infinite loop when server fails
Sometimes, our bot has a peak to 100% CPU because of a server disconnection. Hard to reproduce… Does anyone have met this situation?

### PR DESCRIPTION
**Pull request by Hywan**
Fix #27.

The client now handles all reply codes in range 400-599. This is then possible to catch all errors in the `error` listener. Thus, it's up to the client implementation to decide what to do with these errors.

Please @shulard, can you do a review?

### CODE REVIEW

File: Client.php [hunk 1]
```diff
@@ -129,13 +128,6 @@ protected function _run(HoaSocket\Node $node)
 
                     break;
 
-                case 433: // ERR_NICKNAMEINUSE
-                    throw new Exception(
```
Comment (Hywan) [inline Client.php]: It was caught because `Exception` was extending `Hoa\Exception\Exception` that is extending `Hoa\Exception\Idle`. So the behavior is the same normally. And it is changed, it was a bug, so now it's good ;-).

File: Client.php [hunk 2]
```diff
@@ -129,13 +128,6 @@ protected function _run(HoaSocket\Node $node)
...
-                        'Nickname %s is already in use.',
-                        0,
-                        $node->getUsername()
```
Comment (Hywan) [inline Client.php]: The exception will be caught by the global `try`/`catch`, and it will be fired as an `error` event. In the listener, it will be able to get the current node, so it's fine.

Thoughts?

File: Client.php (hunk 1 above)
Comment (shulard) [inline Client.php]: Ok 👍

File: Client.php (hunk 2 above)
Comment (shulard) [inline Client.php]: If the current node is already accessible in the listener I think it's fine...
